<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kartoffel</string>
		<string>ks</string>
		<string>KartSkp</string>
		<string>de</string>
	</array>
	<key>name</key>
	<string>kartoffelskript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(wahr|falsch)</string>
			<key>name</key>
			<string>constant.language.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(nicht|und|oder)</string>
			<key>name</key>
			<string>keyword.operator.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(mod)</string>
			<key>name</key>
			<string>keyword.operator.kartoffel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>Sei\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.var.kartoffel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\seine?</string>
			<key>name</key>
			<string>markup.other.kartoffel</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:(?!(der|die|das))\S)+\b</string>
					<key>name</key>
					<string>entity.name.tag.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>ist(?=\seine?)</string>
			<key>name</key>
			<string>keyword.operator.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((Ganz|Gleitkomma)zahl|Zeichen(kette)?|Aussage)(-Feld)?</string>
			<key>name</key>
			<string>variable.parameter.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>punctuation.terminator.statement.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[\s\S]+</string>
			<key>name</key>
			<string>comment.line.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>der Größe</string>
			<key>name</key>
			<string>keyword.control.kartoffel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>Setze\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.kartoffel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\sauf</string>
			<key>name</key>
			<string>markup.other.kartoffel</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:(?!(den|die|das))\S)+\b</string>
					<key>name</key>
					<string>support.variable.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(der|die|das|des|dem|ein)\s</string>
			<key>end</key>
			<string>\s</string>
			<key>name</key>
			<string>markup.other.kartoffel</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(leeres Feld|[^\s:]+)</string>
					<key>name</key>
					<string>support.variable.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(Erhöhe|Verringere)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.kartoffel</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ausschließlich numerische Variablen</string>
			<key>end</key>
			<string>\sum</string>
			<key>name</key>
			<string>markup.other.kartoffel</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:(?!(den|die|das))\S)+\b</string>
					<key>name</key>
					<string>support.variable.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>mit dem Wert</string>
			<key>name</key>
			<string>keyword.control.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?\d(,\d)?</string>
			<key>name</key>
			<string>constant.numeric.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>["'][\s\S]+["']</string>
			<key>name</key>
			<string>constant.character.kartoffel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[Ff]ühre den Block</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.kartoffel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>aus</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.kartoffel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.other.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(größer als|kleiner als|größer gleich|kleiner gleich|gleich|ungleich)</string>
			<key>name</key>
			<string>keyword.operator.kartoffel</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kartoffel</string>
	<key>uuid</key>
	<string>6AA8B2FA-7BEA-4364-914A-F5230D79F8A2</string>
</dict>
</plist>
