<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kartoffel</string>
		<string>ks</string>
		<string>de</string>
	</array>
	<key>name</key>
	<string>kartoffelskript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(wahr|falsch)\b</string>
			<key>name</key>
			<string>constant.language.kartoffel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>Sei\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.kartoffel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\seine?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:(?!(der|die|das))\S)+\b</string>
					<key>name</key>
					<string>entity.name.tag.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>ist(?=\seine?)</string>
			<key>name</key>
			<string>keyword.operator.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((Ganz|Gleitkomma)zahl|Zeichen(kette)?|Aussage)(-Feld)?</string>
			<key>name</key>
			<string>support.constant.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>punctuation.terminator.statement.kartoffel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>der Größe</string>
			<key>name</key>
			<string>keyword.control.kartoffel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>Setze\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.kartoffel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\sauf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:(?!(den|die|das))\S)+\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(der|die|das|des|dem|ein)\s</string>
			<key>end</key>
			<string>\s</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>leeres Feld</string>
					<key>name</key>
					<string>storage.modifier.kartoffel</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:(?!((Ganz|Gleitkomma)zahl|Zeichen(kette)?|Aussage)(-Feld)?)[^\s:]+)+\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(Erhöhe|Verringere)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.kartoffel</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ausschließlich numerische Variablen</string>
			<key>end</key>
			<string>\sum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:(?!(den|die|das))\S)+\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.kartoffel</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>mit dem Wert</string>
			<key>name</key>
			<string>keyword.control.kartoffel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([Ff]ühre den Block)\s(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.kartoffel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.kartoffel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})\s(aus)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.kartoffel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.kartoffel</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.kartoffel</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.kartoffel</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
        				(?&lt;!\w|\$)							    # Ensure word boundry
                        [+-]?                                   # Optional sign
        				(?&gt;
        					(
        						(0|[1-9][0-9]*)(\,[0-9]*)?		# 0 or 1 or 1, or 1,0
        					  | \,[0-9]+						# ,1
        					)
        					([eE][+-]?[0-9]+)?					# Exponent
        				)
        				(?!\w)									# Ensure word boundry
        			</string>
					<key>name</key>
					<string>constant.numeric.kartoffel</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>größer als|kleiner als|größer gleich|kleiner gleich|gleich|ungleich</string>
					<key>name</key>
					<string>keyword.operator.comparison.kartoffel</string>
				</dict>
				<dict>
					<key>match</key>
					<string>nicht|und|oder</string>
					<key>name</key>
					<string>keyword.operator.logical.kartoffel</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\:</string>
					<key>name</key>
					<string>keyword.operator.kartoffel</string>
				</dict>
				<dict>
					<key>match</key>
					<string>mod|\*|/|\-|\+</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.kartoffel</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.kartoffel</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.kartoffel</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.kartoffel</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\\n</string>
							<key>name</key>
							<string>constant.character.escape.newline.kartoffel</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\n</string>
							<key>name</key>
							<string>invalid.illegal.character-not-allowed-here.kartoffel</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.kartoffel</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.kartoffel</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\\n</string>
							<key>name</key>
							<string>constant.character.escape.newline.kartoffel</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\n</string>
							<key>name</key>
							<string>invalid.illegal.character-not-allowed-here.kartoffel</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>escapes</key>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{0,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.kartoffel</string>
				</dict>
				<key>interpolation</key>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.kartoffel</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.kartoffel</string>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.kartoffel</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.kartoffel</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.line.kartoffel</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.brace.curly.kartoffel</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.brace.curly.kartoffel</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.kartoffel</string>
	<key>uuid</key>
	<string>6AA8B2FA-7BEA-4364-914A-F5230D79F8A2</string>
</dict>
</plist>
